# Generated by Django 4.2.3 on 2023-10-27 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LAS_LOGs', '0003_link'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Topic',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LAS_LOGs.topic'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
