# Generated by Django 4.2.3 on 2023-10-27 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_topic_alter_tag_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Topic',
        ),
    ]
