# Generated by Django 4.2.3 on 2023-10-30 01:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('LAS_LOGs', '0003_link'),
        ('tags', '0003_remove_tag_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='LAS_LOGs.topic'),
            preserve_default=False,
        ),
    ]
