# Generated by Django 4.2.3 on 2023-11-17 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_user_options_remove_user_date_joined_and_more'),
        ('LAS_LOGs', '0003_link'),
        ('tags', '0004_tag_date_added_tag_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultTopicTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultUserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Tag',
            new_name='TopicTag',
        ),
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='', max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.abstractuser')),
            ],
        ),
    ]
