# Generated by Django 4.2.3 on 2023-11-17 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0015_alter_user_options_remove_user_date_joined_and_more'),
        ('tags', '0005_defaulttopictag_defaultusertag_rename_tag_topictag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertag',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='auth.abstractuser'),
        ),
    ]
