# Generated by Django 4.2.3 on 2023-11-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LAS_LOGs', '0003_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
